version: '3'

volumes:
  pg_data:
  pdf:
  media:
  static:

services:
  
  redis:
    image: redis:alpine
  
  db:
    image: postgres:16.2
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 3s
      retries: 3

  wkhtmltopdf:
    build: ./wkhtmltopdf/
    ports:
      - "127.0.0.1:8001:8001"
    volumes:
      - pdf:/tmp/

  gateway:
    build:
      context: ./gateway/
      dockerfile: ./Dockerfile
    depends_on:
      - backend
    ports:
      - 8000:8000
    volumes:
      - static:/static

  backend:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile-backend
    env_file:
      - path: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static:/backend_static
      - media:/forfar_app/media/pdf

  celery_worker:
    build:
      context: ./backend/
      dockerfile: ./Dockerfile-celery
    env_file:
      - path: .env
    depends_on:
      - redis
      - backend
      - wkhtmltopdf
    command: celery -A forfar worker -l info
    volumes:
      - media:/forfar_app/media/pdf

  celery_beat:
    build: 
      context: ./backend/
      dockerfile: ./Dockerfile-celery
    env_file:
      - path: .env
    depends_on:
      - celery_worker
    command: celery -A forfar beat -l info
    volumes:
      - media:/forfar_app/media/pdf

