version: '3'

volumes:
  pg_data:
  pdf:
  media:
  
services:
  
  redis:
    image: redis:alpine
    # ports:
    #   - "127.0.0.1:6379:6379"
  
  db:
    image: postgres:16.2
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGPORT: 5433
      DB_HOST: db
    ports:
      - "127.0.0.1:5433:5433"

  wkhtmltopdf:
    build: ./wkhtmltopdf/
    ports:
      - "127.0.0.1:8001:8001"
    volumes:
      - pdf:/tmp/

  backend:
    build: ./backend/
    env_file:
      - path: .env
    depends_on:
      - db
      - redis
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - media:/forfar_app/media/pdf

  celery_worker:
    build: ./backend/
    env_file:
      - path: .env
    depends_on:
      - backend
      - wkhtmltopdf
    command: celery -A forfar worker -l info
    volumes:
      - media:/forfar_app/media/pdf

  celery_beat:
    build: ./backend/
    env_file:
      - path: .env
    depends_on:
      - celery_worker
    command: celery -A forfar beat -l info
    volumes:
      - media:/forfar_app/media/pdf


    