# Generated by Django 5.0.2 on 2024-02-16 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='order',
            field=models.JSONField(help_text='информация о заказе'),
        ),
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(help_text='ссылка на созданный PDF-файл', upload_to='pdf'),
        ),
        migrations.AlterField(
            model_name='check',
            name='printer_id',
            field=models.ForeignKey(help_text='\tпринтер', on_delete=django.db.models.deletion.CASCADE, to='core.printer'),
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('1', 'new'), ('2', 'rendered'), ('3', 'printed')], default='1', help_text='статус чека', max_length=50),
        ),
        migrations.AlterField(
            model_name='check',
            name='type',
            field=models.CharField(choices=[('1', 'kitchen'), ('2', 'client')], help_text='тип чека', max_length=50),
        ),
        migrations.AlterField(
            model_name='printer',
            name='api_key',
            field=models.CharField(help_text='ключ доступа к API', max_length=50),
        ),
        migrations.AlterField(
            model_name='printer',
            name='check_type',
            field=models.CharField(choices=[('KT', 'kitchen'), ('CL', 'client')], help_text='тип чека которые печатает принтер', max_length=50),
        ),
        migrations.AlterField(
            model_name='printer',
            name='name',
            field=models.CharField(help_text='название принтера', max_length=50),
        ),
        migrations.AlterField(
            model_name='printer',
            name='point_id',
            field=models.IntegerField(help_text='точка к которой привязан принтер'),
        ),
    ]
