# Generated by Django 5.0.2 on 2024-02-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_check_printer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('NW', 'new'), ('RN', 'rendered'), ('PR', 'printed')], default='NW', help_text='статус чека', max_length=50),
        ),
        migrations.AlterField(
            model_name='check',
            name='type',
            field=models.CharField(choices=[('KT', 'kitchen'), ('CL', 'client')], help_text='тип чека', max_length=50),
        ),
    ]
