# Generated by Django 5.0.2 on 2024-02-16 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('api_key', models.CharField(max_length=50)),
                ('check_type', models.CharField(choices=[('KT', 'kitchen'), ('CL', 'client')], max_length=50)),
                ('point_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('KT', 'kitchen'), ('CL', 'client')], max_length=50)),
                ('order', models.JSONField()),
                ('status', models.CharField(choices=[('NW', 'new'), ('RN', 'rendered'), ('PR', 'printed')], max_length=50)),
                ('pdf_file', models.FileField(upload_to='pdf')),
                ('printer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.printer')),
            ],
        ),
    ]
