# Generated by Django 5.0.2 on 2024-02-16 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_check_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='printer_id',
            field=models.ForeignKey(help_text='принтер', on_delete=django.db.models.deletion.CASCADE, related_name='printers', to='core.printer'),
        ),
    ]
