# Generated by Django 5.0.2 on 2024-02-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_check_status_alter_check_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='ссылка на созданный PDF-файл', null=True, upload_to=''),
        ),
    ]
